Repository gaia-app/gaia, pull requests merged in 2019-11, with the labels that each got.

#151 Timer
  pom.xml
  src/main/java/io/codeka/gaia/stacks/bo/Job.java
  src/main/java/io/codeka/gaia/stacks/workflow/state/PlanFinishedState.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/job.html
  src/main/resources/templates/stack.html
  src/main/resources/templates/vue_templates/job/job-metadata.vue
  src/main/resources/templates/vue_templates/job/job-step.vue
  src/main/resources/templates/vue_templates/job/job-timer.vue
  src/main/resources/templates/vue_templates/stack-vars.vue
  src/test/java/io/codeka/gaia/stacks/bo/JobTest.java
Labels: ✨ feature:jobs, 👌 ready for review, 👤 user:end-user

#167 ✨ : HCL parsing
  pom.xml
  src/main/antlr4/io/codeka/gaia/hcl/antlr/hcl.g4
  src/main/java/io/codeka/gaia/hcl/HclParser.kt
  src/main/java/io/codeka/gaia/hcl/HclVisitor.kt
  src/main/java/io/codeka/gaia/modules/bo/Output.kt
  src/main/java/io/codeka/gaia/modules/bo/TerraformModule.java
  src/main/java/io/codeka/gaia/modules/bo/TerraformVariable.java
  src/main/java/io/codeka/gaia/modules/bo/Variable.kt
  src/main/java/io/codeka/gaia/modules/bo/bo.kt
  src/main/java/io/codeka/gaia/stacks/service/MandatoryStackVariablesValidator.kt
  src/main/java/io/codeka/gaia/stacks/service/RegexStackVariablesValidator.kt
  src/test/java/io/codeka/gaia/hcl/HCLParserTest.java
  src/test/java/io/codeka/gaia/runner/StackCommandBuilderTest.java
  src/test/java/io/codeka/gaia/stacks/service/MandatoryStackVariablesValidatorTest.java
  src/test/java/io/codeka/gaia/stacks/service/RegexStackVariablesValidatorTest.java
  src/test/resources/hcl/outputs.tf
  src/test/resources/hcl/outputs_aws_eks.tf
  src/test/resources/hcl/variables.tf
  src/test/resources/hcl/variables_aws_eks.tf
  src/test/resources/hcl/variables_aws_vpc.tf
Labels: 👌 ready for review

#169 📝 : improve README.md
  README.md
  assets/gaia_logo_with_title.png
  assets/screenshot-gaia-job.png
  assets/screenshot-gaia-module.png
  assets/screenshot-gaia-stack.png
Labels: 👌 ready for review

#174 🐛 : users should be able to edit their modules
  src/main/java/io/codeka/gaia/dashboard/controller/IndexController.java
  src/main/java/io/codeka/gaia/modules/bo/TerraformModule.java
  src/main/java/io/codeka/gaia/modules/controller/ModuleRestController.java
  src/main/java/io/codeka/gaia/modules/controller/ModulesMVCController.java
  src/main/java/io/codeka/gaia/modules/repository/TerraformModuleRepository.java
  src/main/java/io/codeka/gaia/stacks/repository/StackRepository.java
  src/main/java/io/codeka/gaia/teams/controller/TeamsRestController.java
  src/main/resources/templates/modules.html
  src/test/java/io/codeka/gaia/dashboard/controller/IndexControllerTest.java
  src/test/java/io/codeka/gaia/modules/bo/TerraformModuleTest.java
  src/test/java/io/codeka/gaia/modules/controller/ModuleRestControllerIT.java
  src/test/java/io/codeka/gaia/modules/controller/ModuleRestControllerTest.java
  src/test/java/io/codeka/gaia/modules/controller/ModulesMVCControllerTest.java
  src/test/java/io/codeka/gaia/modules/repository/TerraformModuleRepositoryIT.java
  src/test/java/io/codeka/gaia/teams/controller/TeamsRestControllerIT.java
Labels: ✨ feature:modules, 🐛 bug, 👤 user:end-user
