Repository gaia-app/gaia, pull requests merged in 2019-09, with the labels that each got.

#132 ✨ : retry job
  src/main/java/io/codeka/gaia/runner/StackRunner.java
  src/main/java/io/codeka/gaia/stacks/bo/Job.java
  src/main/java/io/codeka/gaia/stacks/controller/JobRestController.java
  src/main/java/io/codeka/gaia/stacks/repository/StepRepository.java
  src/main/java/io/codeka/gaia/stacks/workflow/JobWorkflow.java
  src/main/java/io/codeka/gaia/stacks/workflow/state/ApplyFailedState.java
  src/main/java/io/codeka/gaia/stacks/workflow/state/ApplyFinishedState.java
  src/main/java/io/codeka/gaia/stacks/workflow/state/ApplyStartedState.java
  src/main/java/io/codeka/gaia/stacks/workflow/state/JobState.java
  src/main/java/io/codeka/gaia/stacks/workflow/state/NotStartedState.java
  src/main/java/io/codeka/gaia/stacks/workflow/state/PlanFailedState.java
  src/main/java/io/codeka/gaia/stacks/workflow/state/PlanFinishedState.java
  src/main/java/io/codeka/gaia/stacks/workflow/state/PlanStartedState.java
  src/main/java/io/codeka/gaia/stacks/workflow/state/RetryableState.java
  src/main/resources/templates/job.html
  src/main/resources/templates/vue_templates/job/job-metadata.vue
  src/test/java/io/codeka/gaia/runner/StackRunnerTest.java
  src/test/java/io/codeka/gaia/stacks/bo/JobTest.java
  src/test/java/io/codeka/gaia/stacks/controller/JobRestControllerTest.java
  src/test/java/io/codeka/gaia/stacks/workflow/JobWorkflowTest.java
  src/test/java/io/codeka/gaia/stacks/workflow/state/ApplyFailedStateTest.java
  src/test/java/io/codeka/gaia/stacks/workflow/state/ApplyFinishedStateTest.java
  src/test/java/io/codeka/gaia/stacks/workflow/state/ApplyStartedStateTest.java
  src/test/java/io/codeka/gaia/stacks/workflow/state/NotStartedStateTest.java
  src/test/java/io/codeka/gaia/stacks/workflow/state/PlanFailedStateTest.java
  src/test/java/io/codeka/gaia/stacks/workflow/state/PlanFinishedStateTest.java
  src/test/java/io/codeka/gaia/stacks/workflow/state/PlanStartedStateTest.java
Labels: 👌 ready for review

#143 :bug: : correct job numbering
  src/main/resources/templates/stack.html
Labels: 🐛 bug

#144 🐛 : fix kotlin data classes deserialization
  pom.xml
  src/main/java/io/codeka/gaia/teams/bo.kt
  src/test/java/io/codeka/gaia/teams/controller/TeamsRestControllerIT.java
  src/test/java/io/codeka/gaia/teams/controller/UsersRestControllerIT.java
  src/test/resources/db/00_team.js
  src/test/resources/db/10_user.js
Labels: 🐛 bug, 👌 ready for review
