Repository gaia-app/gaia, pull requests merged in 2019-08, with the labels that each got.

#81 ✨ : add module description screen
  pom.xml
  src/main/java/io/codeka/gaia/controller/TerraformModuleController.java
  src/main/java/io/codeka/gaia/repository/TerraformCLIRepository.java
  src/main/java/io/codeka/gaia/repository/TerraformModuleGitRepository.java
  src/main/java/io/codeka/gaia/repository/strategy/GitHubStrategy.java
  src/main/java/io/codeka/gaia/repository/strategy/GitLabStrategy.java
  src/main/java/io/codeka/gaia/repository/strategy/GitPlatformStrategy.java
  src/main/resources/static/css/github-markdown.css
  src/main/resources/static/css/prism.css
  src/main/resources/static/css/style.css
  src/main/resources/static/images/aws.png
  src/main/resources/templates/job.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/module.html
  src/main/resources/templates/module_description.html
  src/main/resources/templates/modules.html
  src/main/resources/templates/vue_templates/cli-badge.vue
  src/main/resources/templates/vue_templates/readme.vue
  src/test/java/io/codeka/gaia/controller/TerraformModuleControllerTest.java
  src/test/java/io/codeka/gaia/repository/TerraformModuleGitRepositoryTest.java
  src/test/java/io/codeka/gaia/repository/strategy/GitHubStrategyTest.java
  src/test/java/io/codeka/gaia/repository/strategy/GitLabStrategyTest.java
Labels: ✨ enhancement

#78 🚸 : use TF_IN_AUTOMATION env var
  src/main/java/io/codeka/gaia/runner/StackRunner.java
  src/test/java/io/codeka/gaia/runner/StackRunnerTest.java
Labels: ✨ enhancement, 👌 ready for review

#83 💄 : better navigation
  src/main/resources/static/css/style.css
  src/main/resources/templates/empty_page.tpl
  src/main/resources/templates/index.html
  src/main/resources/templates/job.html
  src/main/resources/templates/module.html
  src/main/resources/templates/module_description.html
  src/main/resources/templates/modules.html
  src/main/resources/templates/new_stack.html
  src/main/resources/templates/settings.html
  src/main/resources/templates/stack.html
  src/main/resources/templates/stacks.html
  src/main/resources/templates/vue_templates/breadcrumb.vue
Labels: 👌 ready for review

#85 ✨ : running jobs should be visible in history
  src/main/java/io/codeka/gaia/bo/Job.java
  src/main/java/io/codeka/gaia/controller/StackController.java
  src/main/java/io/codeka/gaia/runner/StackRunner.java
  src/main/resources/templates/stack.html
  src/test/java/io/codeka/gaia/bo/JobTest.java
  src/test/java/io/codeka/gaia/repository/JobRepositoryTest.java
  src/test/java/io/codeka/gaia/runner/StackRunnerTest.java
Labels: ♻ changes required

#86 ✨ : users & teams mgmt
  .travis.yml
  pom.xml
  src/main/java/io/codeka/gaia/bo/Stack.java
  src/main/java/io/codeka/gaia/bo/TerraformModule.java
  src/main/java/io/codeka/gaia/config/RepositoryConfig.java
  src/main/java/io/codeka/gaia/controller/IndexController.java
  src/main/java/io/codeka/gaia/controller/JobRestController.java
  src/main/java/io/codeka/gaia/controller/ModuleRestController.java
  src/main/java/io/codeka/gaia/controller/StackRestController.java
  src/main/java/io/codeka/gaia/controller/TerraformModuleController.java
  src/main/java/io/codeka/gaia/repository/JobRepository.java
  src/main/java/io/codeka/gaia/repository/StackRepository.java
  src/main/java/io/codeka/gaia/repository/StackRepositoryEventHandler.java
  src/main/java/io/codeka/gaia/repository/TerraformModuleRepository.java
  src/main/java/io/codeka/gaia/repository/TerraformStateRepository.java
  src/main/java/io/codeka/gaia/teams/bo/Team.java
  src/main/java/io/codeka/gaia/teams/bo/User.java
  src/main/java/io/codeka/gaia/teams/controller/UserControllerAdvice.java
  src/main/java/io/codeka/gaia/teams/repository/TeamRepository.java
  src/main/java/io/codeka/gaia/teams/repository/UserRepository.java
  src/main/resources/templates/module.html
  src/main/resources/templates/module_description.html
  src/main/resources/templates/new_stack.html
  src/main/resources/templates/stack.html
  src/main/resources/templates/stacks.html
  src/test/java/io/codeka/gaia/bo/TerraformModuleTest.java
  src/test/java/io/codeka/gaia/controller/IndexControllerTest.java
  src/test/java/io/codeka/gaia/controller/JobRestControllerTest.java
  src/test/java/io/codeka/gaia/controller/ModuleRestControllerTest.java
  src/test/java/io/codeka/gaia/controller/StackRestControllerTest.java
  src/test/java/io/codeka/gaia/controller/TerraformModuleControllerTest.java
  src/test/java/io/codeka/gaia/repository/JobRepositoryIT.java
  src/test/java/io/codeka/gaia/repository/SettingsRepositoryIT.java
  src/test/java/io/codeka/gaia/repository/StackRepositoryIT.java
  src/test/java/io/codeka/gaia/repository/TerraformModuleRepositoryIT.java
  src/test/java/io/codeka/gaia/teams/controller/UserControllerAdviceTest.java
  src/test/java/io/codeka/gaia/teams/repository/UserRepositoryTest.java
Labels: 👌 ready for review

#87 ✨ : add team mgmt in ui
  pom.xml
  src/main/java/io/codeka/gaia/controller/ModulesMVCController.java
  src/main/java/io/codeka/gaia/teams/bo/User.java
  src/main/java/io/codeka/gaia/teams/controller/TeamsRestController.java
  src/main/java/io/codeka/gaia/teams/controller/UsersMVCController.java
  src/main/java/io/codeka/gaia/teams/controller/UsersRestController.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/layout/sidebar.html
  src/main/resources/templates/module.html
  src/main/resources/templates/modules.html
  src/main/resources/templates/users.html
  src/main/resources/templates/vue_templates/breadcrumb.vue
  src/test/java/io/codeka/gaia/controller/ModulesMVCControllerTest.java
  src/test/java/io/codeka/gaia/teams/controller/TeamsRestControllerIT.java
  src/test/java/io/codeka/gaia/teams/controller/TeamsRestControllerTest.java
  src/test/java/io/codeka/gaia/teams/controller/UsersRestControllerIT.java
  src/test/java/io/codeka/gaia/teams/controller/UsersRestControllerTest.java
Labels: ✨ enhancement, 👌 ready for review

#89 :lipstick: : add favicon
  src/main/resources/public/favicon.ico
Labels: 🐛 bug, 👌 ready for review

#92 👷 : add discord webhook
  .travis.yml
Labels: ✨ enhancement

#88 ✨ : cost of ownership
  pom.xml
  src/main/java/io/codeka/gaia/bo/Stack.java
  src/main/java/io/codeka/gaia/bo/TerraformModule.java
  src/main/java/io/codeka/gaia/controller/StackRestController.java
  src/main/java/io/codeka/gaia/service/StackCostCalculator.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/job.html
  src/main/resources/templates/module.html
  src/main/resources/templates/module_description.html
  src/main/resources/templates/modules.html
  src/main/resources/templates/new_stack.html
  src/main/resources/templates/stack.html
  src/main/resources/templates/vue_templates/markdown.vue
  src/main/resources/templates/vue_templates/readme.vue
  src/test/java/io/codeka/gaia/controller/StackRestControllerTest.java
  src/test/java/io/codeka/gaia/service/StackCostCalculatorTest.java
Labels: ✨ enhancement, 👌 ready for review

#93 🚸 log user actions
  src/main/java/io/codeka/gaia/bo/Job.java
  src/main/java/io/codeka/gaia/bo/Stack.java
  src/main/java/io/codeka/gaia/controller/StackController.java
  src/main/java/io/codeka/gaia/controller/StackRestController.java
  src/main/java/io/codeka/gaia/repository/TerraformCLIRepository.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/stack.html
  src/main/resources/templates/vue_templates/user-badge.vue
  src/test/java/io/codeka/gaia/bo/JobTest.java
  src/test/java/io/codeka/gaia/controller/StackControllerTest.java
  src/test/java/io/codeka/gaia/controller/StackRestControllerTest.java
  src/test/java/io/codeka/gaia/repository/JobRepositoryIT.java
  src/test/java/io/codeka/gaia/repository/TerraformCLIRepositoryTest.java
  src/test/java/io/codeka/gaia/runner/StackRunnerTest.java
  src/test/java/io/codeka/gaia/service/StackCostCalculatorTest.java
Labels: 👌 ready for review

#101 👷 : corrects integration test inclusion
  pom.xml
Labels: 👌 ready for review

#99 ✨ : database init script
  Dockerfile-db
  README.md
  docker-compose.yml
  src/main/java/io/codeka/gaia/runner/StackCommandBuilder.java
  src/main/java/io/codeka/gaia/runner/StackRunner.java
  src/main/java/io/codeka/gaia/stacks/service/StackCostCalculator.java
  src/main/resources/templates/layout/sidebar.html
  src/main/resources/templates/layout/topbar.html
  src/main/resources/templates/users.html
  src/test/java/io/codeka/gaia/modules/controller/ModuleRestControllerIT.java
  src/test/java/io/codeka/gaia/runner/DockerContainerTest.java
  src/test/java/io/codeka/gaia/runner/StackCommandBuilderTest.java
  src/test/java/io/codeka/gaia/runner/StackRunnerTest.java
  src/test/java/io/codeka/gaia/settings/bo/SettingsTest.java
  src/test/java/io/codeka/gaia/settings/repository/SettingsRepositoryIT.java
  src/test/java/io/codeka/gaia/stacks/bo/JobTest.java
  src/test/java/io/codeka/gaia/stacks/controller/JobRestControllerTest.java
  src/test/java/io/codeka/gaia/stacks/controller/StackControllerTest.java
  src/test/java/io/codeka/gaia/stacks/controller/StackRestControllerIT.java
  src/test/java/io/codeka/gaia/stacks/controller/StackRestControllerTest.java
  src/test/java/io/codeka/gaia/stacks/repository/JobRepositoryIT.java
  src/test/java/io/codeka/gaia/stacks/repository/StackRepositoryIT.java
  src/test/java/io/codeka/gaia/stacks/service/StackCostCalculatorTest.java
  src/test/java/io/codeka/gaia/teams/controller/TeamsRestControllerIT.java
  src/test/java/io/codeka/gaia/teams/controller/TeamsRestControllerTest.java
  src/test/java/io/codeka/gaia/teams/controller/UserControllerAdviceTest.java
  src/test/java/io/codeka/gaia/teams/controller/UsersRestControllerIT.java
  src/test/java/io/codeka/gaia/teams/controller/UsersRestControllerTest.java
  src/test/java/io/codeka/gaia/teams/repository/UserRepositoryTest.java
  src/test/java/io/codeka/gaia/test/MongoContainer.java
  src/test/resources/db/00_team.js
  src/test/resources/db/10_user.js
  src/test/resources/db/20_module.js
  src/test/resources/db/30_stack.js
Labels: ✨ enhancement, 👌 ready for review

#98 👷 : build docker images on tags
  .travis.yml
Labels: 👌 ready for review

#109 🚸 : custom error pages
  src/main/resources/static/images/collision-symbol.png
  src/main/resources/static/images/crying-face.png
  src/main/resources/static/images/no-entry.png
  src/main/resources/templates/error/403.html
  src/main/resources/templates/error/404.html
  src/main/resources/templates/error/500.html
  src/test/java/io/codeka/gaia/test/MongoContainer.java
Labels: ✨ enhancement, 👌 ready for review

#110 🐛 : new users get error page when logging-in
  src/main/java/io/codeka/gaia/dashboard/controller/IndexController.java
  src/main/resources/static/images/waving-hand-sign.png
  src/main/resources/templates/index.html
  src/main/resources/templates/vue_templates/dashboard-widget.vue
  src/test/java/io/codeka/gaia/dashboard/controller/IndexControllerTest.java
Labels: 🐛 bug, 👌 ready for review

#117 🐛 : cards layout
  src/main/resources/templates/modules.html
  src/main/resources/templates/stacks.html
Labels: 🐛 bug, 👌 ready for review

#120 💄 : custom login screen
  src/main/java/io/codeka/gaia/config/SecurityConfig.java
  src/main/java/io/codeka/gaia/config/WebMvcConfig.java
  src/main/resources/static/css/login.css
  src/main/resources/static/favicon.ico
  src/main/resources/templates/login.html
Labels: ✨ enhancement, 👌 ready for review

#123 🐛 : bug fixes on edit module screen
  src/main/resources/templates/module.html
Labels: 🐛 bug, 👌 ready for review

#125 ✨ : navbar footer
  pom.xml
  src/main/java/io/codeka/gaia/config/ActuatorSecurity.java
  src/main/java/io/codeka/gaia/dashboard/controller/DashboardControllerAdvice.java
  src/main/resources/application.properties
  src/main/resources/static/css/responsive.css
  src/main/resources/static/css/style.css
  src/main/resources/templates/layout/sidebar.html
Labels: ✨ enhancement, 👌 ready for review

#126 :see_no_evil: : update dockerignore
  .dockerignore
Labels: 🐛 bug, 👌 ready for review

#129 🚸 : mandatory variables
  pom.xml
  src/main/java/io/codeka/gaia/modules/bo/TerraformModule.java
  src/main/java/io/codeka/gaia/modules/bo/TerraformVariable.java
  src/main/java/io/codeka/gaia/modules/controller/ModuleRestController.java
  src/main/java/io/codeka/gaia/stacks/bo/MandatoryStackVariablesValidation.java
  src/main/java/io/codeka/gaia/stacks/bo/RegexStackVariablesValidation.java
  src/main/java/io/codeka/gaia/stacks/bo/Stack.java
  src/main/java/io/codeka/gaia/stacks/controller/StackRestController.java
  src/main/java/io/codeka/gaia/stacks/controller/StackValidationExceptionHandler.java
  src/main/java/io/codeka/gaia/stacks/service/MandatoryStackVariablesValidator.java
  src/main/java/io/codeka/gaia/stacks/service/RegexStackVariablesValidator.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/layout/sidebar.html
  src/main/resources/templates/module.html
  src/main/resources/templates/new_stack.html
  src/main/resources/templates/stack.html
  src/main/resources/templates/vue_templates/stack-vars.vue
  src/test/java/io/codeka/gaia/modules/controller/ModuleRestControllerIT.java
  src/test/java/io/codeka/gaia/stacks/controller/StackRestControllerIT.java
  src/test/java/io/codeka/gaia/stacks/controller/StackValidationExceptionHandlerTest.java
  src/test/java/io/codeka/gaia/stacks/service/MandatoryStackVariablesValidatorTest.java
  src/test/java/io/codeka/gaia/stacks/service/RegexStackVariablesValidatorTest.java
  src/test/resources/db/20_module.js
Labels: ✨ enhancement, ✨ feature:modules, ✨ feature:stacks, 👌 ready for review, 👤 user:admin, 👤 user:end-user

#130 🐛 keep sidebar status
  src/main/java/io/codeka/gaia/dashboard/controller/DashboardControllerAdvice.java
  src/main/resources/templates/empty_page.tpl
  src/main/resources/templates/index.html
  src/main/resources/templates/job.html
  src/main/resources/templates/layout/sidebar.html
  src/main/resources/templates/module.html
  src/main/resources/templates/module_description.html
  src/main/resources/templates/modules.html
  src/main/resources/templates/new_stack.html
  src/main/resources/templates/settings.html
  src/main/resources/templates/stack.html
  src/main/resources/templates/stacks.html
  src/main/resources/templates/users.html
  src/main/resources/templates/vue_templates/sidebar.vue
Labels: 🐛 bug, 👤 user:admin, 👤 user:end-user

#127 ♻️ : rework of the job management
  src/main/java/io/codeka/gaia/runner/DockerRunner.java
  src/main/java/io/codeka/gaia/runner/StackCommandBuilder.java
  src/main/java/io/codeka/gaia/runner/StackRunner.java
  src/main/java/io/codeka/gaia/stacks/bo/Job.java
  src/main/java/io/codeka/gaia/stacks/bo/JobStatus.java
  src/main/java/io/codeka/gaia/stacks/bo/JobType.java
  src/main/java/io/codeka/gaia/stacks/bo/Step.java
  src/main/java/io/codeka/gaia/stacks/bo/StepStatus.java
  src/main/java/io/codeka/gaia/stacks/bo/StepType.java
  src/main/java/io/codeka/gaia/stacks/controller/JobRestController.java
  src/main/java/io/codeka/gaia/stacks/controller/StackController.java
  src/main/java/io/codeka/gaia/stacks/repository/StepRepository.java
  src/main/java/io/codeka/gaia/stacks/service/StackCostCalculator.java
  src/main/java/io/codeka/gaia/stacks/workflow/JobWorkflow.java
  src/main/java/io/codeka/gaia/stacks/workflow/state/ApplyFailedState.java
  src/main/java/io/codeka/gaia/stacks/workflow/state/ApplyFinishedState.java
  src/main/java/io/codeka/gaia/stacks/workflow/state/ApplyStartedState.java
  src/main/java/io/codeka/gaia/stacks/workflow/state/JobState.java
  src/main/java/io/codeka/gaia/stacks/workflow/state/NotStartedState.java
  src/main/java/io/codeka/gaia/stacks/workflow/state/PlanFailedState.java
  src/main/java/io/codeka/gaia/stacks/workflow/state/PlanFinishedState.java
  src/main/java/io/codeka/gaia/stacks/workflow/state/PlanStartedState.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/job.html
  src/main/resources/templates/new_stack.html
  src/main/resources/templates/stack.html
  src/main/resources/templates/vue_templates/console.vue
  src/main/resources/templates/vue_templates/job/job-apply-confirm.vue
  src/main/resources/templates/vue_templates/job/job-metadata.vue
  src/main/resources/templates/vue_templates/job/job-step.vue
  src/test/java/io/codeka/gaia/runner/DockerRunnerTest.java
  src/test/java/io/codeka/gaia/runner/StackCommandBuilderTest.java
  src/test/java/io/codeka/gaia/runner/StackRunnerTest.java
  src/test/java/io/codeka/gaia/stacks/bo/JobTest.java
  src/test/java/io/codeka/gaia/stacks/bo/StepTest.java
  src/test/java/io/codeka/gaia/stacks/controller/JobRestControllerTest.java
  src/test/java/io/codeka/gaia/stacks/controller/StackControllerTest.java
  src/test/java/io/codeka/gaia/stacks/repository/JobRepositoryIT.java
  src/test/java/io/codeka/gaia/stacks/repository/StepRepositoryIT.java
  src/test/java/io/codeka/gaia/stacks/service/StackCostCalculatorTest.java
  src/test/java/io/codeka/gaia/stacks/workflow/JobWorkflowTest.java
  src/test/java/io/codeka/gaia/stacks/workflow/state/ApplyFailedStateTest.java
  src/test/java/io/codeka/gaia/stacks/workflow/state/ApplyFinishedStateTest.java
  src/test/java/io/codeka/gaia/stacks/workflow/state/ApplyStartedStateTest.java
  src/test/java/io/codeka/gaia/stacks/workflow/state/NotStartedStateTest.java
  src/test/java/io/codeka/gaia/stacks/workflow/state/PlanFailedStateTest.java
  src/test/java/io/codeka/gaia/stacks/workflow/state/PlanFinishedStateTest.java
  src/test/java/io/codeka/gaia/stacks/workflow/state/PlanStartedStateTest.java
Labels: ✨ enhancement, 👌 ready for review
