Repository gaia-app/gaia, pull requests merged in 2019-06, with the labels that each got.

#14 :sparkles: : add docker runner configuration
  README.md
  src/main/java/io/codeka/gaia/bo/Settings.java
  src/main/java/io/codeka/gaia/runner/StackRunner.java
  src/main/java/io/codeka/gaia/runner/config/DockerConfig.java
  src/test/java/io/codeka/gaia/bo/SettingsTest.java
  src/test/java/io/codeka/gaia/runner/config/DockerConfigTest.java
Labels: ✨ enhancement

#15 ✨ : add output block on stack view
  src/main/resources/static/css/prism.css
  src/main/resources/static/css/style.css
  src/main/resources/templates/job.html
  src/main/resources/templates/module.html
  src/main/resources/templates/settings.html
  src/main/resources/templates/stack.html
Labels: ✨ enhancement

#17 :sparkles: : editable variables
  src/main/java/io/codeka/gaia/bo/TerraformVariable.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/module.html
  src/main/resources/templates/stack.html
Labels: ✨ enhancement

#24 🐋 : use latest terraform image
  src/main/java/io/codeka/gaia/runner/StackRunner.java
  src/main/java/io/codeka/gaia/runner/config/DockerConfig.java
Labels: 🐛 bug, 👶 good first issue

#25 🐛 : use module git directory
  src/main/java/io/codeka/gaia/runner/StackCommandBuilder.java
  src/test/java/io/codeka/gaia/runner/StackCommandBuilderTest.java
Labels: 🐛 bug

#27 🔀 : some fixes
  src/main/resources/templates/stack.html
  src/test/java/io/codeka/gaia/bo/SettingsTest.java
Labels: ✨ enhancement, 🐛 bug

#28 🔒 : authentication and basic role mgmt
  pom.xml
  src/main/java/io/codeka/gaia/config/SecurityConfig.java
  src/main/java/io/codeka/gaia/controller/SettingsController.java
  src/main/java/io/codeka/gaia/controller/TerraformModuleController.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/sidebar.html
  src/main/resources/templates/layout/topbar.html
Labels: ✨ enhancement

#32 ✨ : add description to a stack
  src/main/java/io/codeka/gaia/Gaia.java
  src/main/java/io/codeka/gaia/bo/Stack.java
  src/main/resources/templates/stack.html
  src/main/resources/templates/stacks.html
Labels: ✨ enhancement
