Repository gaia-app/gaia, pull requests merged in 2020-01, with the labels that each got.

#197 🐛 : add ui-extensions to login page
  src/main/resources/templates/login.html
Labels: 🐛 bug, 👌 ready for review

#198 ✨ : github module import
  pom.xml
  src/main/java/io/codeka/gaia/Gaia.java
  src/main/java/io/codeka/gaia/config/MongoConfig.java
  src/main/java/io/codeka/gaia/config/security/SecurityConfig.java
  src/main/java/io/codeka/gaia/hcl/HclParserImpl.kt
  src/main/java/io/codeka/gaia/modules/controller/ModuleRestController.java
  src/main/java/io/codeka/gaia/modules/controller/ModulesMVCController.java
  src/main/java/io/codeka/gaia/registries/RegistryApi.kt
  src/main/java/io/codeka/gaia/registries/RegistryRawContent.kt
  src/main/java/io/codeka/gaia/registries/controller/GithubRegistryController.kt
  src/main/java/io/codeka/gaia/registries/github/GitHubRawContent.kt
  src/main/java/io/codeka/gaia/registries/github/GithubRegistryApi.kt
  src/main/resources/application.properties
  src/main/resources/static/css/style.css
  src/main/resources/templates/error/403.html
  src/main/resources/templates/error/500.html
  src/main/resources/templates/modules.html
  src/main/resources/templates/modules_import.html
  src/main/resources/templates/vue_templates/breadcrumb.vue
  src/test/java/io/codeka/gaia/dashboard/controller/UiExtensionsScannerIT.kt
  src/test/java/io/codeka/gaia/hcl/HCLParserTest.java
  src/test/java/io/codeka/gaia/modules/controller/ModuleRestControllerIT.java
  src/test/java/io/codeka/gaia/modules/controller/ModuleRestControllerTest.java
  src/test/java/io/codeka/gaia/modules/controller/ModulesMVCControllerTest.java
  src/test/java/io/codeka/gaia/registries/controller/GithubRegistryControllerTest.kt
  src/test/java/io/codeka/gaia/registries/github/GitHubRawContentTest.java
  src/test/java/io/codeka/gaia/registries/github/GithubRegistryApiTest.kt
  src/test/java/io/codeka/gaia/registries/gitlab/GitLabRawContentTest.java
  src/test/java/io/codeka/gaia/teams/controller/TeamsRestControllerTest.java
Labels: ✨ enhancement, ✨ feature:modules, 👌 ready for review

#201 👷 : update ci for new organization
  .travis.yml
  README.md
  pom.xml
Labels: 👌 ready for review

#208 ✨ : redirect to description page after module import
  src/main/resources/static/css/style.css
  src/main/resources/templates/module_description.html
  src/main/resources/templates/vue_templates/modules/manual-import.vue
  src/main/resources/templates/vue_templates/modules/module-import.vue
  src/test/java/io/codeka/gaia/registries/controller/GithubRegistryControllerIT.kt
  src/test/java/io/codeka/gaia/registries/controller/GitlabRegistryControllerIT.kt
  src/test/resources/rest/github/selmak-public-repos.json
  src/test/resources/rest/github/selmak-terraform-docker-mongo-content-variables.json
  src/test/resources/rest/github/selmak-terraform-docker-mongo.json
  src/test/resources/rest/gitlab/selmak-public-repos.json
  src/test/resources/rest/gitlab/selmak-terraform-docker-mongo-content-variables.json
  src/test/resources/rest/gitlab/selmak-terraform-docker-mongo.json
  src/test/resources/rest/hashicorp/releases.html
Labels: ✅ tests, ✨ enhancement, 👌 ready for review

#214 👥️ : add CODEOWNERS
  .github/CODEOWNERS
Labels: 📝 documentation

#210 ✨ : add module metadata
  src/main/java/io/codeka/gaia/dashboard/controller/IndexController.java
  src/main/java/io/codeka/gaia/modules/bo/ModuleMetadata.kt
  src/main/java/io/codeka/gaia/modules/bo/TerraformModule.java
  src/main/java/io/codeka/gaia/modules/controller/ModuleRestController.java
  src/main/java/io/codeka/gaia/modules/repository/TerraformModuleRepository.java
  src/main/java/io/codeka/gaia/registries/AbstractRegistryApi.kt
  src/main/java/io/codeka/gaia/registries/RegistryRawContent.kt
  src/main/java/io/codeka/gaia/registries/bo.kt
  src/main/java/io/codeka/gaia/registries/config/RegistryConfig.java
  src/main/java/io/codeka/gaia/registries/config/RegistryConfig.kt
  src/main/java/io/codeka/gaia/registries/controller/GithubRegistryController.kt
  src/main/java/io/codeka/gaia/registries/controller/GitlabRegistryController.kt
  src/main/java/io/codeka/gaia/registries/github/GithubRegistryApi.kt
  src/main/java/io/codeka/gaia/registries/gitlab/GitlabRegistryApi.kt
  src/main/java/io/codeka/gaia/registries/service/RegistryService.kt
  src/main/java/io/codeka/gaia/runner/StackCommandBuilder.java
  src/main/resources/templates/module_description.html
  src/main/resources/templates/modules.html
  src/test/java/io/codeka/gaia/dashboard/controller/IndexControllerTest.java
  src/test/java/io/codeka/gaia/modules/bo/TerraformModuleTest.java
  src/test/java/io/codeka/gaia/modules/controller/ModuleRestControllerTest.java
  src/test/java/io/codeka/gaia/modules/repository/TerraformModuleRepositoryIT.java
  src/test/java/io/codeka/gaia/registries/config/RegistryConfigIT.java
  src/test/java/io/codeka/gaia/registries/controller/GithubRegistryControllerIT.kt
  src/test/java/io/codeka/gaia/registries/controller/GithubRegistryControllerTest.kt
  src/test/java/io/codeka/gaia/registries/controller/GitlabRegistryControllerIT.kt
  src/test/java/io/codeka/gaia/registries/controller/GitlabRegistryControllerTest.kt
  src/test/java/io/codeka/gaia/registries/github/GitHubRawContentTest.java
  src/test/java/io/codeka/gaia/registries/github/GithubRegistryApiTest.kt
  src/test/java/io/codeka/gaia/registries/gitlab/GitLabRawContentTest.java
  src/test/java/io/codeka/gaia/registries/service/RegistryServiceImplTest.kt
  src/test/java/io/codeka/gaia/runner/StackCommandBuilderTest.java
  src/test/java/io/codeka/gaia/teams/controller/UsersRestControllerIT.java
  src/test/resources/db/10_user.js
  src/test/resources/db/20_module.js
Labels: ✨ enhancement, ✨ feature:modules, 👌 ready for review, 👤 user:end-user

#215 212 remove moment duration
  pom.xml
  src/main/java/io/codeka/gaia/dashboard/controller/UIExtensionsControllerAdvice.kt
  src/main/resources/templates/index.html
  src/main/resources/templates/job.html
  src/main/resources/templates/module.html
  src/main/resources/templates/module_description.html
  src/main/resources/templates/modules.html
  src/main/resources/templates/modules_import.html
  src/main/resources/templates/new_stack.html
  src/main/resources/templates/settings.html
  src/main/resources/templates/stack.html
  src/main/resources/templates/stacks.html
  src/main/resources/templates/users.html
  src/main/resources/templates/vue_templates/components/breadcrumb.vue
  src/main/resources/templates/vue_templates/components/cli-badge.vue
  src/main/resources/templates/vue_templates/components/console.vue
  src/main/resources/templates/vue_templates/components/dashboard-widget.vue
  src/main/resources/templates/vue_templates/components/job/job-apply-confirm.vue
  src/main/resources/templates/vue_templates/components/job/job-metadata.vue
  src/main/resources/templates/vue_templates/components/job/job-step.vue
  src/main/resources/templates/vue_templates/components/job/job-timer.vue
  src/main/resources/templates/vue_templates/components/markdown.vue
  src/main/resources/templates/vue_templates/components/modules/manual-import.vue
  src/main/resources/templates/vue_templates/components/modules/module-import.vue
  src/main/resources/templates/vue_templates/components/readme.vue
  src/main/resources/templates/vue_templates/components/sidebar.vue
  src/main/resources/templates/vue_templates/components/stack-vars.vue
  src/main/resources/templates/vue_templates/components/user-badge.vue
  src/main/resources/templates/vue_templates/filters/date-time.vue
  src/test/java/io/codeka/gaia/dashboard/controller/UiExtensionsScannerIT.kt
Labels: ♻️ code improvement, ⬆️ dependencies, 👌 ready for review
